# Generated by Django 5.2.16 on 2026-08-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('COURSE', 'Course Mode'), ('LIVE', 'Live Mentoring Mode')], default='COURSE', max_length=10),
        ),
    ]
