# Generated by Django 5.2.16 on 2026-07-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='plagiarism_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='plagiarism_score',
            field=models.PositiveIntegerField(default=0, help_text='Plagiarism score in percentage (0-100)'),
        ),
    ]
