# Generated by Django 4.2 on 2026-07-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('assignments', '0003_assignmentsubmission_plagiarism_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='lesson',
        ),
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='categories.category'),
        ),
    ]
