# Generated by Django 4.2 on 2026-07-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('assignments', '0004_remove_assignment_lesson_assignment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='category',
        ),
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='modules.module'),
        ),
    ]
