# Generated by Django 4.2 on 2026-07-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('assignments', '0005_remove_assignment_category_assignment_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='modules.module'),
        ),
    ]
