# Generated by Django 5.2.16 on 2026-08-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_assignment_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='created_by',
        ),
    ]
