# Generated by Django 5.2.16 on 2026-08-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='staff_type',
            field=models.CharField(choices=[('COURSE', 'Course Mentor'), ('LIVE_CLASS', 'Live Class Staff')], default='COURSE', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('COURSE', 'Course Student'), ('LIVE_CLASS', 'Live Class Student')], default='COURSE', max_length=20),
        ),
    ]
