# Generated by Django 5.2.16 on 2026-08-05 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_staffprofile_staff_type_studentprofile_student_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='staff_type',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assigned_live_staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_live_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('COURSE', 'Course Student'), ('LIVE_CLASS', 'Live Class Student'), ('BOTH', 'Both')], default='COURSE', max_length=20),
        ),
    ]
