# Generated by Django 5.2.16 on 2026-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_created_by'),
        ('users', '0006_remove_staffprofile_staff_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='categories',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='courses.course'),
        ),
    ]
