# Generated by Django 5.2.16 on 2026-08-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_studentprofile_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='first_login',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
