# Generated by Django 5.2.16 on 2026-08-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_studentattendance_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
