# Generated by Django 5.2.16 on 2026-07-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_issued',
            field=models.BooleanField(default=True),
        ),
    ]
