# Generated by Django 5.2.16 on 2026-07-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_retries',
            field=models.PositiveIntegerField(default=3, help_text='Maximum allowed attempts'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='randomize_questions',
            field=models.BooleanField(default=True, help_text='Randomize question sequence for students'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='timer_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Time limit in minutes'),
        ),
    ]
