# Generated by Django 4.2 on 2026-07-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_remove_quiz_lesson_quiz_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=50, help_text='Percentage required to pass (default 50% = at least half correct)'),
        ),
    ]
