# Generated by Django 5.2.16 on 2026-08-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_quiz_passing_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='max_retries',
            field=models.PositiveIntegerField(default=10, help_text='Maximum allowed attempts'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=0, help_text='Percentage required to pass (default 0% = at least half correct)'),
        ),
    ]
