# Generated by Django 5.2.16 on 2026-07-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_banner_course_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(blank=True, default='Apex Instructor', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_role',
            field=models.CharField(blank=True, default='Instructor / Coordinator', max_length=150, null=True),
        ),
    ]
