# Generated by Django 4.2 on 2026-07-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_by',
        ),
    ]
