# Generated by Django 4.2 on 2026-07-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('courses', '0009_liveclass_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_classes', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='courses.course'),
        ),
    ]
