# Generated by Django 4.2 on 2026-07-29 03:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_liveclass_category_alter_liveclass_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='assigned_live_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
