# Generated by Django 5.2.16 on 2026-08-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_liveclass_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='recording_url',
            field=models.URLField(blank=True, help_text='URL for the recorded session after completion', null=True),
        ),
    ]
