# Generated by Django 5.2.16 on 2026-08-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_liveclass_recording_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_mentoring_track',
            field=models.BooleanField(default=False, help_text='True if this is a recorded sessions track'),
        ),
    ]
