# Generated by Django 5.2.16 on 2026-08-08 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursediscussionpost',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='courses.course'),
        ),
    ]
