# Generated by Django 5.2.16 on 2026-08-19 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='viewed_recording_students',
            field=models.ManyToManyField(blank=True, related_name='viewed_live_recordings', to=settings.AUTH_USER_MODEL),
        ),
    ]
