# Generated by Django 5.2.16 on 2026-07-10 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_additional_notes_lesson_external_links_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=10, help_text='Estimated study duration in minutes'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text="List of FAQs e.g. [{'q': 'question', 'a': 'answer'}]"),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='watch_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='watch_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LessonBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_seconds', models.FloatField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position_seconds'],
            },
        ),
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
