# Generated by Django 4.2 on 2026-07-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_estimated_duration_lesson_faqs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
